In [1]:
import polars as pl
import pandas as pd
import xarray as xr
import numpy as np
from jax import numpy as jnp, jit
from itertools import product, combinations, permutations
from bidict import bidict

In [2]:
from summer3.proto import CompartmentMap, Stratification

In [3]:
age_strat = Stratification("age", ["infant", "child", "adult", "older"])

cm = CompartmentMap.new(age_strat)

In [4]:
disease_state = cm.stratify(Stratification("disease_state", ["S","I","R"]))

In [5]:
locx = np.arange(8)
locy = np.arange(8)
loc_strata = [f"loc_{i}" for i,s in enumerate(product(locx, locy))]

In [6]:
loc_strat = cm.stratify(Stratification("loc", loc_strata))

In [6]:
data = cm.zeros()

In [9]:
ma = data.as_managed_array()

In [10]:
from summer3.utils import get_unique_keyname

In [ ]:
# Unifying access across
# 1d vs Nd
# Compartment


class PAccessExpr:
    def __init__(self, pl_expr, pa):
        self.pl_expr = pl_expr
        self.pa = pa

    def __and__(self, other):
        return PAccessExpr(self.pl_expr & other.pl_expr, self.pa)
    
    def __invert__(self):
        return PAccessExpr(~self.pl_expr, self.pa)
    
    def __repr__(self):
        return f"PAccessExpr[{self.pa}] {self.pl_expr}"

class PropertyAccessor:
    # prop_key is probably a Stratification for our first example
    def __init__(self, prop_key, ptable):
        self.prop_key = prop_key
        self._ptable = ptable

        self._uname = uname = ptable.su[prop_key]
        self._pik_map = ptable.uname_propidxkey_map[uname]

    def __repr__(self):
        return f"PropertyAccessor[{self.prop_key}]"

    def __map_args__(self, args):
        try:
            iargs = self._pik_map.inverse[args]
        except:
            iargs = [self._pik_map.inverse[a] for a in args]

        return iargs

    def is_in(self, args):
        if isinstance(args, str):
            args = [args]
        iargs = self.__map_args__(args)
        pl_expr = pl.col(self._uname).is_in(iargs)
        return PAccessExpr(pl_expr, self)

In [53]:
class PropertyTable:
    def __init__(self, uname_strat_map, uname_propidxkey_map, prop_table):
        self.uname_strat_map = uname_strat_map
        self.uname_propidxkey_map = uname_propidxkey_map
        self.table = prop_table

        self.us = self.uname_strat_map
        self.su = self.uname_strat_map.inverse

        self.properties = self.__build_accessors__()

    def __build_accessors__(self):
        return {k:PropertyAccessor(k, self) for k in self.uname_strat_map.inverse}

def build_property_tables(cm, compartments):
    # Stratifications do not require unique names
    # but we need unique strings for non-object supporting 
    # table keys (polars etc)
    uname_strat_map = bidict()
    uname_propidxkey_map: dict[str,bidict] = {}
    _prop_tab = {}
    for strat in cm.stratifications:
        name = strat.name
        uname = get_unique_keyname(name, uname_strat_map)
        uname_strat_map[uname] = strat
        _prop_tab[uname] = v = np.empty(len(compartments), dtype=int)
        v.fill(-1)
        uname_propidxkey_map[uname] = bidict({i:k for (i,k) in enumerate(strat.strata)})
    
    for comp_i,c in enumerate(compartments):
        for strat, stratum in c.strata:
            uname = uname_strat_map.inverse[strat]
            ik_map = uname_propidxkey_map[uname]
            prop_i = ik_map.inverse[stratum]
            _prop_tab[uname][comp_i] = prop_i

    prop_table = pl.DataFrame(_prop_tab | {"index": np.arange(len(compartments))})

    return PropertyTable(uname_strat_map, uname_propidxkey_map, prop_table)

In [54]:
prop_table = build_property_tables(cm, cm.compartments)

In [58]:
prop_table.properties[disease_state].is_in(["S","R"])

PAccessExpr[PropertyAccessor[Stratification: disease_state]] col("disease_state_0").is_in([[0, 2]])

In [19]:
def pfilter(ptable: PropertyTable, strat, op, args, inv=False):
    uname = ptable.su[strat]
    pik_map = ptable.uname_propidxkey_map[uname]
    try:
        iargs = pik_map.inverse[args]
    except:
        iargs = [pik_map.inverse[a] for a in args]
    if inv:
        return ptable.table.filter(~getattr(pl.col(uname), op)(iargs))
    else:
        return ptable.table.filter(getattr(pl.col(uname), op)(iargs))

In [20]:
col = pl.col("age_0")

In [ ]:
age_pa = PropertyAccessor(age_strat, prop_table)
disease_pa = PropertyAccessor(disease_state, prop_table)

q = age_pa.is_in(["child"]) and ~disease_pa.is_in("S")

prop_table.table.filter(q.pl_expr)

shape: (8, 3)
┌───────┬─────────────────┬───────┐
│ age_0 ┆ disease_state_0 ┆ index │
│ ---   ┆ ---             ┆ ---   │
│ i64   ┆ i64             ┆ i64   │
╞═══════╪═════════════════╪═══════╡
│ 0     ┆ 1               ┆ 1     │
│ 0     ┆ 2               ┆ 2     │
│ 1     ┆ 1               ┆ 4     │
│ 1     ┆ 2               ┆ 5     │
│ 2     ┆ 1               ┆ 7     │
│ 2     ┆ 2               ┆ 8     │
│ 3     ┆ 1               ┆ 10    │
│ 3     ┆ 2               ┆ 11    │
└───────┴─────────────────┴───────┘

In [22]:
prop_table.table.filter(pl.col("age_0").is_between(1,2) & pl.col("disease_state_0").is_in([0,2]))

shape: (4, 3)
┌───────┬─────────────────┬───────┐
│ age_0 ┆ disease_state_0 ┆ index │
│ ---   ┆ ---             ┆ ---   │
│ i64   ┆ i64             ┆ i64   │
╞═══════╪═════════════════╪═══════╡
│ 1     ┆ 0               ┆ 3     │
│ 1     ┆ 2               ┆ 5     │
│ 2     ┆ 0               ┆ 6     │
│ 2     ┆ 2               ┆ 8     │
└───────┴─────────────────┴───────┘

In [ ]:
def get_pmask(prop_dict, ptable: PropertyTable):
    for strat, strata in prop_dict.items():

In [15]:
prop_table.uname_propidxkey_map[prop_table.su[age_strat]].inverse["child"]

1

In [18]:
prop_table.table

shape: (12, 3)
┌───────┬─────────────────┬───────┐
│ age_0 ┆ disease_state_0 ┆ index │
│ ---   ┆ ---             ┆ ---   │
│ i64   ┆ i64             ┆ i64   │
╞═══════╪═════════════════╪═══════╡
│ 0     ┆ 0               ┆ 0     │
│ 0     ┆ 1               ┆ 1     │
│ 0     ┆ 2               ┆ 2     │
│ 1     ┆ 0               ┆ 3     │
│ 1     ┆ 1               ┆ 4     │
│ …     ┆ …               ┆ …     │
│ 2     ┆ 1               ┆ 7     │
│ 2     ┆ 2               ┆ 8     │
│ 3     ┆ 0               ┆ 9     │
│ 3     ┆ 1               ┆ 10    │
│ 3     ┆ 2               ┆ 11    │
└───────┴─────────────────┴───────┘

In [17]:
ptt = pfilter(age_strat, "is_in", ["infant","child"])

[0, 1]

In [ ]:
# is_tiling_dim
# Can we reshape this array such that a new axis
# constructed from this dimension will have equal tiling
# with regards to other data

In [91]:
cdata = cm.wrap_data(jnp.arange(0,len(cm.compartments))).as_managed_array()

In [92]:
cdata.data

Array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767], dtype=int64)

In [121]:
cm.query([(age_strat, ["child","older"]),(loc_strat, ["loc_0","loc_5"])])

CompartmentContainer view of 0x2531430577360:
array([Compartment :[(Stratification: age, 'child'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'child'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'child'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'child'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'child'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'child'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'older'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'older'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'older'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'older'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'older'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'older'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'R')]],
      dtype=object)array([192, 193, 194, 207, 208, 209, 576, 577, 578, 591, 592, 593])

In [113]:
def is_valid_tiling_dim(dim_col, ptable):
    active_col = dim_col
    nicols = ptable.columns
    nicols.remove('index')
    nicols.remove(active_col)

    ref = None

    for col_val in ptt[active_col].unique():
        comp = ptable.filter(pl.col(active_col).eq(col_val))[nicols]
        if ref is not None:
            if not comp.equals(ref):
                return False
            ref = comp
    
    return True

In [ ]:
# Folding/Unfolding
# Consider the inverse case first;
# N-properties with perfect encompassing tiling
# represented as Nd MA, with N dims each having 1 property
# 
# What transforms can we do on this that we can prove
# retain some or all of these properties?

#
#  
#

shape: (768, 4)
┌───────┬───────┬─────────────────┬───────┐
│ age_0 ┆ loc_0 ┆ disease_state_0 ┆ index │
│ ---   ┆ ---   ┆ ---             ┆ ---   │
│ i64   ┆ i64   ┆ i64             ┆ i64   │
╞═══════╪═══════╪═════════════════╪═══════╡
│ 0     ┆ 0     ┆ 0               ┆ 0     │
│ 0     ┆ 0     ┆ 1               ┆ 1     │
│ 0     ┆ 0     ┆ 2               ┆ 2     │
│ 0     ┆ 1     ┆ 0               ┆ 3     │
│ 0     ┆ 1     ┆ 1               ┆ 4     │
│ …     ┆ …     ┆ …               ┆ …     │
│ 3     ┆ 62    ┆ 1               ┆ 763   │
│ 3     ┆ 62    ┆ 2               ┆ 764   │
│ 3     ┆ 63    ┆ 0               ┆ 765   │
│ 3     ┆ 63    ┆ 1               ┆ 766   │
│ 3     ┆ 63    ┆ 2               ┆ 767   │
└───────┴───────┴─────────────────┴───────┘

In [118]:
is_valid_tiling_dim("disease_state_0", prop_table.table)

True

In [95]:
ptt["disease_state_0"].value_counts()["count"].unique()

shape: (1,)
Series: 'count' [u32]
[
	192
]

In [74]:
ptidx = prop_table.table.filter(~pl.col("age_0").gt(0))["index"]

In [77]:
cm.compartments[ptidx]

array([Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_1'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_1'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_1'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_2'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_2'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_2'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_3'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_3'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_3'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_4'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_4'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_4'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_6'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_6'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_6'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_7'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_7'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_7'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_8'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_8'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_8'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_9'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_9'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_9'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_10'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_10'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_10'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_11'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_11'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_11'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_12'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_12'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_12'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_13'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_13'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_13'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_14'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_14'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_14'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_15'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_15'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_15'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_16'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_16'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_16'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_17'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_17'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_17'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_18'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_18'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_18'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_19'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_19'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_19'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_20'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_20'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_20'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_21'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_21'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_21'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_22'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_22'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_22'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_23'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_23'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_23'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_24'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_24'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_24'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_25'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_25'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_25'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_26'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_26'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_26'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_27'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_27'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_27'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_28'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_28'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_28'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_29'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_29'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_29'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_30'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_30'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_30'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_31'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_31'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_31'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_32'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_32'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_32'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_33'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_33'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_33'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_34'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_34'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_34'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_35'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_35'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_35'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_36'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_36'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_36'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_37'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_37'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_37'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_38'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_38'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_38'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_39'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_39'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_39'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_40'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_40'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_40'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_41'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_41'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_41'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_42'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_42'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_42'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_43'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_43'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_43'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_44'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_44'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_44'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_45'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_45'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_45'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_46'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_46'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_46'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_47'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_47'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_47'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_48'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_48'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_48'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_49'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_49'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_49'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_50'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_50'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_50'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_51'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_51'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_51'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_52'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_52'), (Stratification: disease_state, 'I')],

In [33]:
list(cm.stratifications)[0].strata

('infant', 'child', 'adult', 'older')

In [ ]:
cm.stratifications

for c in data.compartments:
    c.strata

array([Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_0'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_1'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_1'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_1'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_2'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_2'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_2'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_3'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_3'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_3'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_4'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_4'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_4'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_5'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_6'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_6'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_6'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_7'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_7'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_7'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_8'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_8'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_8'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_9'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_9'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_9'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_10'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_10'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_10'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_11'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_11'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_11'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_12'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_12'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_12'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_13'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_13'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_13'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_14'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_14'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_14'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_15'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_15'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_15'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_16'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_16'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_16'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_17'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_17'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_17'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_18'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_18'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_18'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_19'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_19'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_19'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_20'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_20'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_20'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_21'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_21'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_21'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_22'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_22'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_22'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_23'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_23'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_23'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_24'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_24'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_24'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_25'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_25'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_25'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_26'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_26'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_26'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_27'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_27'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_27'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_28'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_28'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_28'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_29'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_29'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_29'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_30'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_30'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_30'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_31'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_31'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_31'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_32'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_32'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_32'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_33'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_33'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_33'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_34'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_34'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_34'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_35'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_35'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_35'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_36'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_36'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_36'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_37'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_37'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_37'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_38'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_38'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_38'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_39'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_39'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_39'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_40'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_40'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_40'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_41'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_41'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_41'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_42'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_42'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_42'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_43'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_43'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_43'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_44'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_44'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_44'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_45'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_45'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_45'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_46'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_46'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_46'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_47'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_47'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_47'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_48'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_48'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_48'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_49'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_49'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_49'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_50'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_50'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_50'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_51'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_51'), (Stratification: disease_state, 'I')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_51'), (Stratification: disease_state, 'R')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_52'), (Stratification: disease_state, 'S')],
       Compartment :[(Stratification: age, 'infant'), (Stratification: loc, 'loc_52'), (Stratification: disease_state, 'I')],